# Generated by Django 4.0 on 2021-12-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jasperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_threads', models.ManyToManyField(to='reddit.NewsCatagory')),
                ('saved_posts', models.ManyToManyField(to='reddit.PostContainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
