# Generated by Django 4.0 on 2021-12-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCatagory',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('img', models.TextField()),
                ('upvotes', models.TextField(default='0')),
                ('time', models.IntegerField()),
                ('deletion_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('news_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.newscatagory')),
            ],
        ),
        migrations.CreateModel(
            name='PostContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.IntegerField()),
                ('saved_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='parent_reddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit'),
        ),
    ]
